// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./MedicalInvoiceVerifier.sol";  // auto-generated by snarkjs

contract MedicalBillingRegistry {

    MedicalInvoiceVerifier public verifier;

    struct InvoiceRecord {
        bytes32 commitment;    // Poseidon hash of private data
        uint256 coverageLimit;
        address submitter;
        uint256 timestamp;
        bool    verified;
        string  ipfsCID;       // link to encrypted invoice on Filecoin/IPFS
    }

    mapping(bytes32 => InvoiceRecord) public invoices;
    mapping(address => bytes32[])     public providerInvoices;

    event InvoiceVerified(bytes32 indexed commitment, address indexed provider, string cid);

    constructor(address _verifier) {
        verifier = MedicalInvoiceVerifier(_verifier);
    }

    function submitInvoice(
        uint256[2]    calldata a,          // proof.pi_a
        uint256[2][2] calldata b,          // proof.pi_b
        uint256[2]    calldata c,          // proof.pi_c
        uint256[2]    calldata pubSignals, // [invoice_commitment, is_valid]
        uint256       coverageLimit,
        string        calldata ipfsCID
    ) external {
        // 1. Verify the ZK proof on-chain
        bool valid = verifier.verifyProof(a, b, c, pubSignals);
        require(valid, "Invalid ZK proof");
        require(pubSignals[1] == 1, "Invoice constraints not satisfied");

        bytes32 commitment = bytes32(pubSignals[0]);
        require(invoices[commitment].timestamp == 0, "Invoice already submitted");

        // 2. Store verified record — no private patient data stored on-chain
        invoices[commitment] = InvoiceRecord({
            commitment:    commitment,
            coverageLimit: coverageLimit,
            submitter:     msg.sender,
            timestamp:     block.timestamp,
            verified:      true,
            ipfsCID:       ipfsCID
        });

        providerInvoices[msg.sender].push(commitment);
        emit InvoiceVerified(commitment, msg.sender, ipfsCID);
    }

    function isVerified(bytes32 commitment) external view returns (bool) {
        return invoices[commitment].verified;
    }

    function getProviderInvoices(address provider) external view returns (bytes32[] memory) {
        return providerInvoices[provider];
    }
}
