const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    const [deployer] = await ethers.getSigners();
    const network    = await ethers.provider.getNetwork();
    console.log("Deploying on chainId:", network.chainId.toString());
    console.log("Deployer:", deployer.address);

    // FraudVerifier.sol is auto-generated by Sindri — must exist before running this
    if (!fs.existsSync(path.join(__dirname, "../contracts/FraudVerifier.sol"))) {
        throw new Error(
            "contracts/FraudVerifier.sol not found.\n" +
            "Run the Sindri circuit compilation first:\n" +
            "  node zkml/sindriService.js (uploadAndCompileCircuit)"
        );
    }

    // 1. Deploy FraudVerifier (Sindri-generated)
    const FraudVerifier = await ethers.getContractFactory("FraudVerifier");
    const fraudVerifier = await FraudVerifier.deploy();
    await fraudVerifier.waitForDeployment();
    const fraudVerifierAddr = await fraudVerifier.getAddress();
    console.log("FraudVerifier:", fraudVerifierAddr);

    // 2. Deploy FraudRegistry wrapping the verifier
    const FraudRegistry = await ethers.getContractFactory("FraudRegistry");
    const fraudRegistry = await FraudRegistry.deploy(fraudVerifierAddr);
    await fraudRegistry.waitForDeployment();
    const fraudRegistryAddr = await fraudRegistry.getAddress();
    console.log("FraudRegistry:", fraudRegistryAddr);

    // Update calibration.json with new addresses
    const deployFile = path.join(__dirname, "../deployments/calibration.json");
    const existing   = JSON.parse(fs.readFileSync(deployFile));
    const updated    = {
        ...existing,
        fraudVerifier: fraudVerifierAddr,
        fraudRegistry: fraudRegistryAddr,
        fraudUpdatedAt: new Date().toISOString(),
    };
    fs.writeFileSync(deployFile, JSON.stringify(updated, null, 2));
    console.log("\nUpdated deployments/calibration.json");
    console.log("\nNext step: redeploy MedicalBillingRegistry with fraudRegistry address.");
    console.log("  npx hardhat run scripts/deploy.js --network calibration");
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
