// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

// AUTO-GENERATED by snarkjs — do not edit manually.
// Replace this file by running:
//   snarkjs zkey export solidityverifier build/medical_invoice_final.zkey contracts/MedicalInvoiceVerifier.sol
// Then rename the contract from Groth16Verifier → MedicalInvoiceVerifier.

contract MedicalInvoiceVerifier {
    function verifyProof(
        uint256[2]    calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2]    calldata _pC,
        uint256[2]    calldata _pubSignals  // [invoice_commitment, is_valid]
    ) public view returns (bool) {
        // Placeholder — replaced after running compile.sh from Stage 1
        revert("Verifier not yet generated. Run compile.sh first.");
    }
}
